### ISSUE TITLE
Topsy + non-Topsy keys at the same time cause _many_ repeated keys

### ISSUE THREAD

**Issue by indirect** [keyboardio/Kaleidoscope-TopsyTurvy#6] opened 2017-10-16 05:56 UTC
I'm working on a layer that includes numbers on the left hand and symbols on the right. The relevant bit looks like this:

```
[SYMBOL] =  KEYMAP_STACKED
  (___,   ___,   ___,   ___,   ___,   ___,   ___,
   ___, Key_1, Key_2, Key_3, Key_4, Key_5, ___,
        Key_6, Key_7, Key_8, Key_9, Key_0, ___,
   ___, ___,   ___,   ___,   ___,   ___,   ___,
   ___, ___,   ___,   ___,
   ___,

   ___, ___,      ___,      ___,      ___,      ___,      ___,
   ___, TOPSY(1), TOPSY(2), TOPSY(3), TOPSY(4), TOPSY(5), ___,
        TOPSY(6), TOPSY(7), TOPSY(8), TOPSY(9), TOPSY(0), ___,
   ___, ___,      ___,      ___,      ___,      ___,      ___,
   ___, ___,      ___,      ___,
   ___)
```

For some reason, when typing (for example) `Key_7` and `TOPSY(6)` at the same time, the output is not `7^`, or even `&^`, but instead `^&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&7`. That is... many more letters than I was expecting. Here's a gif trying to demonstrate, but keep in mind that I am pressing keys at the same speed the entire time it's recording:

![](http://files.arko.net/383C1N3k1l0x/Screen%20Recording%202017-10-15%20at%2010.53%20PM.gif)

**Comment by algernon** [comment] 2017-10-16 06:28
This appears to be somewhat similar to #5, and is a... hard cookie to crack, so to say. I have a few ideas, but will need to check which one works.

**Comment by twopir** [comment] 2017-10-27 03:47
I'm also seeing this on my Model 01.

**Comment by gedankenexperimenter** [comment] 2017-11-22 17:15
I was just combing through the code while working on designing a similar, but more flexible plugin, and suspected I'd see something like this, tried it out, then went to report the issue, and wished I'd looked here first. =P

I have a solution in mind, which is to use both the `eventHandlerHook` and the (pre-clear) `loopHook`, and instead of sending an injected event, call `hid::releaseRawKey()` for any keys that need the "wrong" `shift` state to clear them from the report before it gets sent.  This becomes complicated, however, if you have two different keys defined as `Key_N` & `TOPSY(N)`, because they share the same bit in the HID report.  That's not likely to be a real problem for this plugin, but it is something I intend to deal with, because I also want to allow dissociating the two symbols that share a keycode (e.g. a key that's `,`/`;`).

Then we just need to decide an overlap suppression strategy: which key(s) get masked when there's overlap? The ones that want the "wrong" shift state? The most recent key toggled on wins? The key(s) already held win?

**Comment by lldata** [comment] 2018-02-04 21:10
I just tried what I thought was a very simple mapping and also got the repeated keys issue.
Does TOPSY work under any circumstances? Is there any tricks / workarounds you can suggest @algernon ?

**Comment by rosskevin** [comment] 2018-03-08 15:37
I just encountered this with `TOPSY(Semicolon)`.  If a workaround or different plugin/strategy works, please let me know.

**Comment by ckamm** [comment] 2018-05-12 08:55
I also have the repeated-key issue: a very simple config with `TOPSY(Minus)` sends lots of keypresses when the key is used together with the shift key.

**Comment by TreTuna** [comment] 2018-07-10 21:23
Trying to use to invert all my number keys and having this issue when shifted as well.

**Comment by algernon** [comment] 2018-08-26 19:51
I have a fix for the case where topsy + non-topsy are used together. I have an idea for the shift+topsy case too. Should have a fix soon!

**Comment by algernon** [comment] 2018-08-26 20:05
Okay, I'm going to mark this as a duplicate of #5, because the original report is the same problem. There is another issue, `Shift+TOPSY` behaving similarly weird, but the root cause there is different, and will need a slightly different fix. I'll open a new issue about that.

**Closed by algernon** 2018-08-26 20:05 UTC
Labels: bug, duplicate
